name: Auto label owner PRs

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  label:
    if: github.repository_owner == github.event.pull_request.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Ensure automerge label exists
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = 'automerge';
            try {
              await github.rest.issues.getLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: labelName,
              });
            } catch (error) {
              if (error.status === 404) {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: labelName,
                  color: '2ea043',
                  description: 'Automatically merge pull requests when all checks pass',
                });
              } else {
                throw error;
              }
            }
      - name: Add automerge label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = 'automerge';
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [labelName],
            });
