name: QA Lighthouse

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site and install Chromium
        run: npm run pretest:a11y

      - name: Run Lighthouse accessibility checks
        run: npm run test:a11y

      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
