name: QA Lighthouse (Nightly)

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

concurrency:
  group: qa-lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Detect Playwright version
        id: playwright-version
        run: |
          node <<'NODE' >> "$GITHUB_OUTPUT"
          import { readFileSync } from 'node:fs';
          const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
          console.log(`version=${pkg.devDependencies.playwright}`);
          NODE
        shell: bash

      - name: Cache npm directory
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          NPM_CONFIG_CACHE: ~/.npm

      - name: Build site and prepare Lighthouse bundle
        run: |
          npm run build
          node scripts/prepare-lhci-dist.mjs
        env:
          NPM_CONFIG_CACHE: ~/.npm

      - name: Install Chromium via Playwright (disabled on CI)
        if: ${{ runner.os == 'Linux' && false }}
        run: node scripts/setup-playwright.mjs

      - name: Setup Chromium
        id: setup-chromium
        uses: browser-actions/setup-chromium@v1

      - name: Set CHROME_PATH
        run: echo "CHROME_PATH=${{ steps.setup-chromium.outputs.chromium-path }}" >> $GITHUB_ENV

      - name: Run Lighthouse accessibility checks
        run: npm run test:a11y

      - name: Run /deals/ QA checks
        run: node scripts/run-deals-qa.mjs

      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report-nightly
          path: .lighthouseci
